# Generated by Django 4.2.1 on 2023-05-09 05:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_alter_book_category_alter_book_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="book",
            name="name",
            field=models.CharField(default="", max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="book",
            name="price",
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
    ]
