# Generated by Django 4.2.1 on 2023-05-09 05:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_alter_book_description_alter_book_name_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Book_Author",
        ),
    ]
