# Generated by Django 4.2.1 on 2023-05-11 00:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_alter_book_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="book_image",
            field=models.ImageField(null=True, upload_to="images"),
        ),
    ]
