# Generated by Django 4.2.1 on 2023-05-16 04:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0008_alter_customer_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="modified_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="total",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=5, null=True
            ),
        ),
    ]
