# Generated by Django 4.2.1 on 2023-05-16 04:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0009_alter_customer_modified_on_alter_order_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="price",
            field=models.DecimalField(decimal_places=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="total",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=20, null=True
            ),
        ),
    ]
