# Generated by Django 4.2.1 on 2023-05-16 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0010_alter_book_price_alter_order_total"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OrderDetails",
            new_name="OrderDetail",
        ),
        migrations.AlterField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.customer",
            ),
        ),
    ]
